### PR TITLE
Upgrade to sbt 1.0

### LINKED ISSUE #19: Migrate build to sbt 1
This project should be migrated to sbt 1.0. I believe it may not be trivial because we are using some APIs that were removed.

### PR DESCRIPTION
**Pull request by ignasi35**
Fixes #19 
Upgrades the build to sbt 1.0

### CODE REVIEW

**Comment by ignasi35** [comment]
Did a first pass. The bulk of the changes pending is on:

https://github.com/playframework/omnidoc/blob/74c95ccaa2dda6265e5decd2a1295194f9ba2bc0/project/OmnidocBuild.scala#L195-L204

Causing the errors:

```
[error] /Users/ignasi/git/projects/lightbend/playframework/omnidoc/project/OmnidocBuild.scala:200:64: type mismatch;
[error]  found   : String
[error]  required: sbt.librarymanagement.ConfigRef
[error]     val playModules       = update.value.configuration(Omnidoc.name).toSeq.flatMap(_.allModules.filter(playModuleFilter))
[error]                                                                ^
[error] /Users/ignasi/git/projects/lightbend/playframework/omnidoc/project/OmnidocBuild.scala:201:29: not found: value GetClassifiersModule
[error]     val classifiersModule = GetClassifiersModule(projectID.value, playModules, Seq(Omnidoc), transitiveClassifiers.value)
[error]                             ^
[error] /Users/ignasi/git/projects/lightbend/playframework/omnidoc/project/OmnidocBuild.scala:202:29: not found: value GetClassifiersConfiguration
[error]     val classifiersConfig = GetClassifiersConfiguration(classifiersModule, Map.empty, updateConfiguration.value, ivyScala.value)
[error]                             ^
[error] /Users/ignasi/git/projects/lightbend/playframework/omnidoc/project/OmnidocBuild.scala:202:114: not found: value ivyScala
[error]     val classifiersConfig = GetClassifiersConfiguration(classifiersModule, Map.empty, updateConfiguration.value, ivyScala.value)
[error]                                                                                                                  ^
[error] /Users/ignasi/git/projects/lightbend/playframework/omnidoc/project/OmnidocBuild.scala:203:5: not found: value IvyActions
[error]     IvyActions.updateClassifiers(ivySbt.value, classifiersConfig, quietLogger(streams.value.log))
[error]     ^
``` 

------------------
The other pending change is moving all the code from `project/Build.scala` to `build.sbt`.

**Comment by ignasi35** [comment]
This is shaping up well.

Currently, I only get small differences on the generated HTML of the javadocs:

```
Files javadoc/deprecated-list.html and golden/javadoc/deprecated-list.html differ
Files javadoc/overview-tree.html and golden/javadoc/overview-tree.html differ
Files play/data/format/package-tree.html and golden/javadoc/play/data/format/package-tree.html differ
Files javadoc/play/data/validation/package-tree.html and golden/javadoc/play/data/validation/package-tree.html differ
Files javadoc/play/filters/csrf/package-tree.html and golden/javadoc/play/filters/csrf/package-tree.html differ
Files javadoc/play/mvc/Action.html and golden/javadoc/play/mvc/Action.html differ
Files javadoc/play/mvc/package-tree.html and golden/javadoc/play/mvc/package-tree.html differ
```

-------------------------------

The main cause of code changes was modifications on the visibility and behavior of Ivy dependency resolution. Omnidoc downloads `src`, `docs` and `playdoc` versions of several artifacts. The issue, I think, is that while `src` and `docs` are first class, well-known identifiers, `playdoc` is not and internal changes between `0.13` and `1.0` (or underlying ivy client libraries) broke how the `playdoc` artifacts were downloaded.

**Comment by ignasi35** [comment]
I've done a review of the diff's and it's all differences in sorting the elements on the HTML lists. I think the output is correct.

**Comment by ignasi35** [comment]
> Nicely done

Wouldn't have done it without your help. :-)

**Comment by dwijnand** [comment]
I dunno, your follow-up diff is some impressive work.

**Pull request merged**
